# Generated by Django 5.1.5 on 2025-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('blog_author', models.CharField(max_length=255)),
            ],
        ),
    ]
