# Generated by Django 5.1.5 on 2025-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_user_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
